apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.{{ required "`.Values.groupName` is required" .Values.groupName }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/{{ .Release.Name }}"
spec:
  groupPriorityMinimum: 1000
  versionPriority: 15
  group: {{ .Values.groupName }}
  version: v1alpha1
  service:
    name: {{ .Release.Name }}
    namespace: {{ .Release.Namespace }}