apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appname" . }}
  labels:
    app: {{ include "appname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "appname" . }}
  template:
    metadata:
      name: {{ include "appname" . }}
      labels:
        app: {{ include "appname" . }}
    spec:
      volumes:
        - name: tls
          secret:
            secretName: {{ include "appname" . }}
      serviceAccountName: {{ include "appname" . }}
      containers:
        - name: {{ include "appname" . }}
          image: '{{ .Values.webhook.image.repository }}:{{ default .Chart.Version .Values.webhook.image.tag }}'
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /tls
              name: tls
          env:
            - name: GROUP_NAME
              value: {{ .Values.groupName }}
            - name: CERT_MANAGER_NAMESPACE
              value: {{ .Values.certManager.namespace }}
            {{- range $name, $value := .Values.webhook.envs }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          args:
            - --tls-cert-file=/tls/tls.crt
            - --tls-private-key-file=/tls/tls.key
          resources:
            {{- toYaml .Values.webhook.resources | nindent 12 }}
          ports:
            - containerPort: 443
              name: https
          readinessProbe:
            httpGet:
              port: https
              path: /healthz
            initialDelaySeconds: 5
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 5
            periodSeconds: 4
      restartPolicy: Always
