name: build push docker image

on:
  push:
    branches:
      - main
      - dev
      - dev/*
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - uses: ko-build/setup-ko@v0.8
      - run: ko build --sbom=none --bare -t ${{ github.ref_name }}